version: '3.5'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    environment:
      - APP_PORT=3000
      - PG_HOST=db
      - PG_PORT=5432
      - PG_USERNAME=postgres
      - PG_PASSWORD=postgres
      - PG_DATABASE=base
      - JWT_SECRET_KEY=7f23d42198a3b688f7094df24f17a018dde8390869212eae9d5f00cebfac6457
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=base
    container_name: postgres
    ports:
      - 35000:5432